import { fetcher } from "@/utils/fetcher";
import twemoji from "twemoji";
import Head from "next/head";
import useSWR from "swr";
import { CountryGrid } from "@/components/CountryGrid/CountryGrid";

export type Country = {
  name: {
    common: string;
    official: string;
  };
  population: number;
  region: string;
  subregion: string;
  capital: string[];
  currencies: {
    [code: string]: {
      name: string;
      symbol: string;
    };
  };
  languages: {
    [code: string]: string;
  };
  flag: string;
  area: number;
};

export default function Home() {
  const {
    data: countries,
    error,
    isLoading,
  } = useSWR<Country[]>("https://restcountries.com/v3.1/all", fetcher);

  if (error) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CountryGrid countries={countries} />
    </>
  );
}
